function A_m = Am_tmp(l1,l2,l3,m,m3,q1_m,q2_m,q3_m)
%AM_TMP
%    A_M = AM_TMP(L1,L2,L3,M,M3,Q1_M,Q2_M,Q3_M)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    15-Oct-2019 12:20:21

t2 = l2.^2;
t3 = -q2_m;
t4 = -q3_m;
t5 = q1_m+t3;
t6 = q2_m+t4;
t7 = cos(t5);
t8 = cos(t6);
A_m = reshape([l1.*m.*(l1-l2.*t7.*2.0).*(-1.0./4.0),l1.^2.*m.*(-1.0./4.0),0.0,m.*t2.*(-5.0./4.0)-m3.*t2+(l1.*l2.*m.*t7)./2.0-(l2.*l3.*m3.*t8)./2.0,0.0,0.0,l3.*m3.*(l3+l2.*t8.*2.0).*(-1.0./4.0),0.0,l3.^2.*m3.*(-1.0./4.0)],[3,3]);
