function A_p = Ap_tmp(l1,l2,l3,m,m3,q1_p,q2_p,q3_p)
%AP_TMP
%    A_P = AP_TMP(L1,L2,L3,M,M3,Q1_P,Q2_P,Q3_P)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    15-Oct-2019 12:20:22

t2 = l1.^2;
t3 = -q2_p;
t4 = -q3_p;
t5 = q1_p+t3;
t6 = q1_p+t4;
t7 = cos(t5);
t8 = cos(t6);
A_p = reshape([m.*t2.*(-5.0./4.0)-m3.*t2+(l1.*l2.*m.*t7)./2.0-(l1.*l3.*m3.*t8)./2.0,0.0,0.0,l2.*m.*(l2-l1.*t7.*2.0).*(-1.0./4.0),l2.^2.*m.*(-1.0./4.0),0.0,l3.*m3.*(l3+l1.*t8.*2.0).*(-1.0./4.0),0.0,l3.^2.*m3.*(-1.0./4.0)],[3,3]);
